### ISSUE TITLE
[Blocked] node can accept adapter connections 

### ISSUE THREAD

**Issue by mkolehmainen** [org-zpr/zpr-core#17]
Listen on a public address, on a port.  (no visa auth yet)

A user can fire up an adapter configured to connect to a node.  The connection is successful which you can see by looking at the log output on the the node.

The node will send and respond to keep alive messages in zdp from the adapter. 

Blocked by:
- org-zpr/zpr-core#15
- org-zpr/zpr-core#18  - Is this story actually a dupe?

**Comment by cpacejo** [comment]
Completed by #379.
