### ISSUE TITLE
[Blocked] adapter can open a connection to node v0 (EPIC)

### ISSUE THREAD

**Issue by mkolehmainen** [org-zpr/zpr-core#18]
Adapter Can Open A Connection to  a node is composed of-

- org-zpr/zpr-core#251
- org-zpr/zpr-core#17
- org-zpr/zpr-core#27
- org-zpr/zpr-core#228
- org-zpr/zpr-core#252

Blocked by:
- org-zpr/zpr-core#15

**Comment by cpacejo** [comment]
Completed by #379.
