### ISSUE TITLE
[Blocked] client adapter can forward agent packets over an open connection to the node

### ISSUE THREAD

**Issue by mkolehmainen** [org-zpr/zpr-core#19]
Needs to pick up packets from TUN, forward across the tether, and deliver the responses.

Here's an idea for the enterprising developer - script the other side of this such that you can perfrom the setup and other "node" responses.  See SCAPY.

Blocked by:
- org-zpr/zpr-core#17
- org-zpr/zpr-core#18

**Comment by cpacejo** [comment]
Addressed by #379.
