### ISSUE TITLE
Adapter - Node connection with stubbed auth

### ISSUE THREAD

**Issue by mkolehmainen** [org-zpr/zpr-core#228]
As part of the Adapter Connects To Node epic.  In org-zpr/zpr-core#18 we set up so that a node and adapter can exchange ZDP keep alive messages, but all auth has been skipped.  In this story we add some auth placeholders.  At the end of the connection the adapter and the node have exchanged certificates.

There is an external write up on this connection process.

The process is- 

1. adapter sends key message to know with adapter cert.
2. node responds with key message to adapter with node cert.
3. node sends auth request to adapter
4. adapter responds to auth request
5. boom - connected!

Blocked by
- org-zpr/zpr-core#18

Related:
- org-zpr/zpr-core#17

**Comment by cpacejo** [comment]
Subsumed by #252 and #353.
