### ISSUE TITLE
request/reply handler -- no retries

### ISSUE THREAD

**Issue by cpacejo** [org-zpr/zpr-core#264]
To support synchronous management messages we'll need a request/reply handler.  [§ 6.4](https://docs.google.com/document/d/1W0NDiHSKVvnVx5QytaxD00uUaoA6t9YU/edit#heading=h.3abhhcj) of the RFC defines how this functionality should work, but there are some open questions which need resolving so let's just implement what I've got below for now.

First we'll need some state to track outstanding synchronous requests.  Let's call this `SyncReqState<'pktbuf>`.  It should live in the `Assembly`.  It should have two members, one an inner struct (call it `SyncReqInnerState<'pktbuf>`) protected by an std `Mutex`, and the other, a [`tokio::sync::Semaphore`](https://docs.rs/tokio/latest/tokio/sync/struct.Semaphore.html).

The `SyncReqInnerState` for now will just have a [`Option<tokio::sync::oneshot::Sender<Packet<'pktbuf>>>`](https://docs.rs/tokio/latest/tokio/sync/oneshot/struct.Sender.html) as a member, call it `reply_channel`.  It will grow other members later once we (Sarah Frank & I) sort out how sequence numbers work.

`SyncReqState` should have a `new()` method to initialize it – initialize `reply_channel` as `None`, and the semaphore with `Semaphore::new(1)` (i.e. it has one permit).  Going forward, a node will create a new `SyncReqState` per link, but for now we'll just have the one which is a member of the `Assembly`.

The purpose of `SyncReqState` is to track outstanding synchronous requests which other parts of the PH make.  When making a request, the requestor acquires a permit from the semaphore (to make sure that at most we have 1 oustanding request) and registers a new `OneShot` channel in the `reply_channel` field, and wait on that for a response.  Then, `inbound_processor`, upon receipt of a reply, will check `reply_channel`, if there's something there, send the reply there.  That will wake up the requestor, which then releases the permit and continues on its way.

So – for the requestor, let's add a pair of async methods on the `Assembly`, call them `send_sync_non_flow_req()` and `send_sync_per_flow_req()`.  They'll have the same arguments for now as the corresponding `enqueue_*_mgmt()` methods on the outbound processor, except they should have two `ZdpPacketType` arguments (one for request type one for response type), and should return a `std::result::Result<Packet<'pktbuf>, SyncReqError>` (for non-flow) or `std::result::Result<(u32, Packet<'pktbuf>), SyncReqError>` (for per-flow; the `u32` is the returned flow ID).  (Define `SyncReqError` as an enum with two values for now, `LinkClosed` and `ProtocolError`.)  These method should do a few things:

1. Acquire a permit from the `SyncReqState`.
2. [Create](https://docs.rs/tokio/latest/tokio/sync/oneshot/fn.channel.html) a `OneShot` receiver/sender pair.
3. Acquire the mutex in `SyncReqState`.
4. Assign the `OneShot` sender to `reply_channel`.
5. Release the mutex.  (This you can do by placing steps 3 & 4 in braces, so the mutex is released when the scope exits.)
6. Enqueue a mgmt message with the outbound processor using the appropriate method.
7. `.await` the `OneShot` receiver.  If you get an error due to the channel being closed, return a `SyncReqError::LinkClosed` error.
8. Return the semaphore permit.  You can do this with `std::mem::drop()`.
9. Confirm that the reply message type corresponds to the request message type.  If they don't match, destroy the packet, return the buffer to the buffer pool, increment a counter (you'll have to make a new one, call it `BadMgmtResponse` or such), and return `ProtocolError`.
10. For the per-flow case, copy out the stream ID.
11. Remove the base message header or flow message header using `.advance()`.
12. Return the `Packet`, along with the stream ID in the per-flow case.

On the flip side of things, we'll need to teach `inbound_processor` about replies.  Here, you'll want to check if a received message is a response using `ZdpMessageType::is_response()`.  If it is, the inbound processor should grab the `SyncReqState` mutex, check `reply_channel` for a channel, if there is one, send the packet on it.  (You'll need to use `Option::take()` to move the sender out, since sending consumes the sender.  & you can drop the mutex immediately after calling `Option::take()`.)  If there's no reply channel (it's already `None`) or the send fails – drop the packet and count it.  (We'll need another new counter, call it `UnexpectedMgmtResponse` or such.)

This should do it for now!  Later we'll add the capability to timeout and retry, and to check sequence numbers.

**Comment by owenrhysthomas** [comment]
In the final paragraph, you say "If it is, the outbound processor should grab the SyncReqState mutex, check reply_channel for a channel...". I assume you mean inbound processor because I'm not sure how the outbound processor could perform actions based on conditionals in the inbound processor. Also earlier in the task description you said said the `reply_channel` handling should occur in the `inbound_processor`. If this is an incorrect assumption, let me know.

**Comment by cpacejo** [comment]
Yes correct that was a braino, fixed!  (Also made an edit about using `Option::take()` to get at the sender.)
