### ISSUE TITLE
node listens for and accepts a visa service connection

### ISSUE THREAD

**Issue by mkolehmainen** [org-zpr/zpr-core#27]
See our PKI write up (*). 

The node during startup will accept a connection from the visa service adapter based on a well known value in the x509 certificate CN field.  Once the node has determined that the VS adapter has connected, it needs to access the visa service registration function through the VS thrift API (see org-zpr/zpr-core#146)
Previously Blocked by:
- org-zpr/zpr-core#17
- org-zpr/zpr-core#419
- org-zpr/zpr-core#34

**Comment by cpacejo** [comment]
Note: the carrier should only come up on the node if either (a) we connect to another node, or (b) the visa server connects to us.
