### ISSUE TITLE
Figure out why PH tokio isn't using multiple OS threads

### ISSUE THREAD

**Issue by mkolehmainen** [org-zpr/zpr-core#42]
Despite that we're using [`Builder::new_multi_thread()`](https://docs.rs/tokio/latest/tokio/runtime/struct.Builder.html#method.new_multi_thread), the Tokio runtime in the PH appears to be running only on one OS thread.  (This can be seen by running a workload through the PH, and observing in `top -H` that only one thread is using 100% of its core.)

Looking now this might be as simple as using the [`Builder::worker_threads()`](https://docs.rs/tokio/latest/tokio/runtime/struct.Builder.html#method.worker_threads) method, but it should be defaulting to the number of cores on the system, not 1.

The [`Runtime::metrics()`](https://docs.rs/tokio/latest/tokio/runtime/struct.Runtime.html#method.metrics) method might be useful to figure out what's going on too.

It's also possible that, since the DTLS worker is the primary source of CPU-intensive work, Tokio realizes this and doesn't bother spinning up other OS threads for the other workers.  It would be nice to understand the mechanism behind this choice if this is true.

**Comment by cpacejo** [comment]
I'm OK to call this done for now!  You found the answer to the original question (Tokio _is_ using multiple OS threads).  We do need a deeper performance dive, given the messy performance profile you found Tokio to have, but let's hold off on that for a bit.
