### ISSUE TITLE
tool to create a CSR (and keys)

### ISSUE THREAD

**Issue by mkolehmainen** [org-zpr/zpr-core#45]
New zpr tool we can use to create a keypair and a csr.  For now we just use a CN in the CSR subject (TODO: that's fine, right?).

The command should be flexible enough to generate a new keypair or use an existing key.  So for example:

For example,
```bash
$ ./zprauth create
Usage:
   create csr [--key private key] CN 
   create key
```

```bash
$ ./zprauth create csr adapter1.blah
wrote private key to adapter1.blah.private
wrote public key to adapter1.blah.public
wrote csr to adapter1.blah.csr
```

```bash
$ ./zprauth create csr --key mykey.private adapter1.blah
wrote csr to adapter1.blah.csr
``` 

Maybe even just `create key` should work too:

```bash
$ ./zprauth create key 
wrote private key to adapter.private
wrote public key to adapter.public
```

Bonus points for coming up with a better name than "zprauth". 

This could probably be expanded to run CA duties too, which would take some of the pain out of setup and testing for those who are not running a full-fledges key management system already.  But that's another story.

**Comment by cpacejo** [comment]
See here for some helpful commands: https://gitlab.appliedinvention.com/surenet/surenet/-/wikis/OpenSSL-%22micro%22-CA-basics
