### ISSUE TITLE
policy compiler: allow ICMP(v6) type 0

### ISSUE THREAD

**Issue by cpacejo** [org-zpr/zpr-core#573]
There are two issues here:

1) the prototype zpl compiler treats ICMP type codes the same as ports -- that is, it runs them through the same syntax checks, so zero is not allowed.

2) the prototype zpl compiler was written to only support IPv6 and hence only ICMP6 which is not supposed to use type code 0.

So to fix this we need to alter prototype compiler (ask mathias what branch) to allow value 0.  We possibly need to add ICMPv4 and ICMPv6 as separate protocols but I'm not 100% sure of that.  I may have already allowed fro that in the policy enforcer so that needs to be checked with a unit test or something.

**Comment by mkolehmainen** [comment]
The `refimpl-m2` branch now allows type 0.  Looking now at the matcher code which I think is ICMPv6 only.
